name: Cypress test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: npm install
      - name: Test
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          # browser: firefox
