name: Cypress test

on: 
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use (electron, chrome, chromium, edge, firefox)'
        default: 'electron'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: cypress-io/github-action@v6
        with:
          command: npm install
      - name: Test
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser ${{ inputs.browser }}
