name: Cypress test

on: 
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'electron'
        required: true
        type: choice
        options:
        - electron
        - chrome
        - chromium
        - edge
        - firefox

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: cypress-io/github-action@v6
        with:
          command: npm install
      - name: Test
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser ${{ inputs.browser }}
